### ISSUE TITLE
saveToGallery

### ISSUE THREAD

**Issue by kivzark** [nicloay/colorus#1]
Thank you for this lovely code nicolay,
i'm trying to run it on mi Ipad but i got this error in xcode linking : 

Undefined symbols for architecture armv7:
  "_saveToGallery", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o

Do you have any idea how to resolve this issue ?

Thanks in advance

**Comment by nicloay** [comment]
Thanks @kivzark 

As i've told in readme.md file. I've used 3d party software. ScreenshotGallery is one of them. You don't have to use this plugin. and what you can to do is just search in project [ScreenshotManager](https://github.com/nicloay/colorus/search?utf8=✓&q=screenshot) and remove or just replace this usages. also you should delete Assets/Plugins/ScreenshotManager.cs class
