### ISSUE TITLE
Does it port to android easily?

### ISSUE THREAD

**Issue by cowboybkit** [nicloay/colorus#2]
Hi, 

```
I want to port to android, what time does it take?
```

Thanks

**Comment by nicloay** [comment]
I haw no any idea how long would it take for you. and i don't event know what doesn't work with android there.
Maybe would be better to port part by part if you can split project logically.

**Comment by rraallvv** [comment]
@cowboybkit, I made a fix for Android in a PR, if you get a chance could you please confirm it's working?

**Comment by rraallvv** [comment]
@nicloay any idea why the drawing is so slow?

**Comment by nicloay** [comment]
Because it use [Get|Set]Pixels for drawing. To make it works fast need to use render texture and shader approach as i do here http://paintcraft.in/coop/v3/

**Comment by rraallvv** [comment]
@nicloay 
I see... thanks for the quick reply, I'll give it a try.
Keep up the good work!
